test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -21,7 +21,7 @@ jobs:
           echo "private1=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list" >> $GITHUB_ENV
           echo "private2=https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/all.txt" >> $GITHUB_ENV
           echo "ads=https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml" >> $GITHUB_ENV
-          echo "ad_white=https://raw.githubusercontent.com/privacy-protection-tools/dead-horse/refs/heads/master/anti-ad_white-for-clash.yaml" >> $GITHUB_ENV
+          echo "ad_white=https://raw.githubusercontent.com/privacy-protection-tools/dead-horse/refs/heads/master/anti-ad-white-for-clash.yaml" >> $GITHUB_ENV
           echo "my_ad_white=https://raw.githubusercontent.com/crawlingsnailatb/domain-list-custom/refs/heads/master/myfile/my-white-list.yaml" >> $GITHUB_ENV
           echo "games_cn1=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.list" >> $GITHUB_ENV
           echo "games_cn2=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.list" >> $GITHUB_ENV
@@ -102,7 +102,14 @@ jobs:
       - name: Generate ad-white
         run: |
           curl -sSL ${my_ad_white} | grep -Ev '#|payload:' | sed -e '/^\s*$/d' -e "s/'$//" -e 's/^[ \t]*//' -e "s/^- '+\./DOMAIN-SUFFIX,/" -e "s/^- '/DOMAIN,/" | sort --ignore-case > ./domains/my-ad-white.list
+          if [ ! -f ./domains/my-ad-white.list ]; then
+          echo "Error: my-ad-white.list not created."
+          exit 1
+          fi
+          
           grep -Fx -f ./domains/ads.list ./domains/my-ad-white.list > ./domains/duplicates.txt
+          echo "Error: not grep"
+          
           grep -Fvxf ./domains/duplicates.txt ./domains/ads.list > ./domains/ads.list.tmp
           mv ./domains/ads.list.tmp ./domains/ads.list
           grep -Fvxf ./domains/duplicates.txt ./domains/my-ad-white.list > ./domains/my-ad-white.tmp
